### ISSUE TITLE
Catch TTransportException and rethrow an UnavailableExpception

### ISSUE THREAD

**Issue by fduan** [posulliv/libcassandra#3]
In CassandraFactory::createThriftClient method, it throws an exception if the connection could not be made.

```
 transport->open(); /* throws an exception */
```

Should this exception be caught and rethrow an UnavialableException?

**Comment by posulliv** [comment]
Well, that depends. The application could catch the exception at its level. If the connection can not be made, a TTransportException is thrown from Thrift which seems like a pretty good exception to throw to me.

I figured there was no need to add a new exception type since I could just catch that exception type in my application. 

I can add in a new exception if that is really desired though?

**Comment by fduan** [comment]
No. I think it is okay for now. Thanks.
