### ISSUE TITLE
Unable to remove an entire row specified by a key

### ISSUE THREAD

**Issue by themanatuf** [posulliv/libcassandra#8]
I'm trying to remove an entire row from a standard column but validateColumnPath keeps throwing an exception because col_path.column is empty. According to the Cassandra API:

```
Note that all the values in column_path besides column_path.column_family are truly optional:...
```

Is there a way around this or am I doing something wrong? The code I'm executing that is generating the exception is as follows:

```
CassandraFactory(DBHOST, 9160);
tr1::shared_ptr<Cassandra> client(factory.create());
Keyspace *key_space = client->getKeyspace("Keyspace1");
key_space->remove("OrgName", "Organization", "", "");
delete key_space;
```

Any help would be appreciated. Thanks.

**Comment by posulliv** [comment]
Thanks for the bug report.

You are totally right. The column path validation was being called from the remove function within libcassandra and checking to make sure column is not empty.

This is un-necessary for the remove function since its possible to call remove with just a column family name and a key.

I've updated the 0.6.5 branch of libcassandra to include a fix for this. I'll be pushing to fix to the master branch sometime this week probably.

Thanks again.
Padraig
